import { useEffect, useState, useMemo, useRef } from 'react';
import { Sparkles, RefreshCw, AlertCircle, ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useAISummary } from '@/hooks/useAISummary';
import { useAuth } from '@/hooks/useAuth';
import { useAiInsightsSettings, currentAiInsightsPeriodKey } from '@/hooks/useAiInsightsSettings';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';

interface AISummaryCardProps {
  page: string;
  role?: string;
  data: Record<string, any>;
  className?: string;
  autoGenerate?: boolean;
}

function buildCacheKey(scope: string, page: string, data: Record<string, any>): string {
  // v5: keys are scoped by user+org — a cached summary is one tenant's financial
  // data and must never surface for the next account that signs in on this browser.
  try {
    return `ai-summary-v5-${scope}-${page}-${JSON.stringify(data)}`;
  } catch {
    return `ai-summary-v5-${scope}-${page}`;
  }
}

/* ── SuperAdmin-controlled generation schedule ───────────────────────────
   For daily/weekly/monthly modes, a generated summary is kept in localStorage
   (keyed by PAGE, not by the data snapshot — the whole point is to not
   regenerate on every figure change) stamped with the period it was generated
   in. It is reused while the current period matches; the first visit after a
   boundary (new day / chosen weekday / chosen month date) regenerates.
   'session' mode keeps the legacy per-session behaviour. Manual refresh
   always overrides. */
const scheduleCacheKey = (scope: string, page: string, role: string) => `ai-summary-sched-v2-${scope}-${page}-${role}`;

// One-off purge of the unscoped v1 entries: they persist across logins, so a
// summary generated by one tenant's account was shown to the next account that
// signed in on the same browser.
try {
  for (const key of Object.keys(localStorage)) {
    if (key.startsWith('ai-summary-sched-v1-')) localStorage.removeItem(key);
  }
} catch {}

function readScheduleCache(scope: string, page: string, role: string, periodKey: string): string | null {
  try {
    const raw = localStorage.getItem(scheduleCacheKey(scope, page, role));
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { text?: string; period?: string };
    if (!parsed?.text || parsed.period !== periodKey) return null;
    return parsed.text;
  } catch {
    return null;
  }
}

function writeScheduleCache(scope: string, page: string, role: string, text: string, periodKey: string | null): void {
  if (!periodKey) return;
  try {
    localStorage.setItem(scheduleCacheKey(scope, page, role), JSON.stringify({ text, period: periodKey }));
  } catch {}
}

function clearScheduleCache(scope: string, page: string, role: string): void {
  try { localStorage.removeItem(scheduleCacheKey(scope, page, role)); } catch {}
}

/** Force £ in AI text when the model (or an old cache) used $. */
function normalizeAiSummaryGbp(text: string): string {
  if (!text || !text.includes('$')) return text;
  return text
    .replace(/-\$/g, '-£')
    .replace(/\$/g, '£');
}

/** Status accents for the model's ✓ / ⚠ / ✗ bullet symbols. */
type Accent = 'good' | 'warn' | 'bad' | null;

const ACCENT_TEXT: Record<Exclude<Accent, null>, string> = {
  good: 'text-emerald-600 dark:text-emerald-400',
  warn: 'text-amber-600 dark:text-amber-400',
  bad: 'text-red-600 dark:text-red-400',
};

function statusOf(symbol: string): Exclude<Accent, null> {
  if (symbol === '✓' || symbol === '✅') return 'good';
  if (symbol === '⚠' || symbol === '⚠️') return 'warn';
  return 'bad';
}

/** Inline rendering: `**bold**` + coloured ▲/▼ arrows, no markdown dependency.
    Inside a status bullet the arrows take the bullet's accent (a rising cost in
    a ⚠ bullet must not render green); elsewhere they colour by direction. */
function InlineText({ text, accent = null }: { text: string; accent?: Accent }) {
  const parts = text.split(/(\*\*[^*]+\*\*|[▲▼][^\s,;)]*|✓|✅|⚠️|⚠|✗|✘|❌)/g);
  return (
    <>
      {parts.map((part, i) => {
        if (part.startsWith('**') && part.endsWith('**')) {
          return (
            <strong key={i} className="font-semibold text-foreground">
              {part.slice(2, -2)}
            </strong>
          );
        }
        if (part.startsWith('▲') || part.startsWith('▼')) {
          const cls = accent
            ? ACCENT_TEXT[accent]
            : part.startsWith('▲') ? ACCENT_TEXT.good : ACCENT_TEXT.bad;
          return (
            <span key={i} className={cn('font-medium', cls)}>
              {part}
            </span>
          );
        }
        if (/^(✓|✅|⚠️|⚠|✗|✘|❌)$/.test(part)) {
          // Status glyph the model placed mid-line — colour it in place.
          return (
            <span key={i} className={cn('font-semibold', ACCENT_TEXT[statusOf(part)])}>
              {statusOf(part) === 'good' ? '✓' : statusOf(part) === 'warn' ? '⚠' : '✗'}
            </span>
          );
        }
        return <span key={i}>{part}</span>;
      })}
    </>
  );
}

/** Renders the model's compact summary: bold headline, status bullets
    (✓ / ⚠ / ✗) with coloured symbols and direction arrows. */
function SummaryText({ text }: { text: string }) {
  const blocks = useMemo(() => {
    const out: Array<{ type: 'p' | 'h' | 'ul'; items: string[] }> = [];
    for (const raw of text.split('\n')) {
      const line = raw.trim();
      if (!line) continue;
      if (/^#{1,4}\s+/.test(line)) {
        out.push({ type: 'h', items: [line.replace(/^#{1,4}\s+/, '')] });
      } else if (/^[-*•]\s+/.test(line)) {
        const item = line.replace(/^[-*•]\s+/, '');
        const prev = out[out.length - 1];
        if (prev?.type === 'ul') prev.items.push(item);
        else out.push({ type: 'ul', items: [item] });
      } else {
        out.push({ type: 'p', items: [line] });
      }
    }
    return out;
  }, [text]);

  return (
    <div className="space-y-2.5">
      {blocks.map((block, i) => {
        if (block.type === 'h') {
          return (
            <p key={i} className="text-sm font-semibold text-foreground">
              <InlineText text={block.items[0]} />
            </p>
          );
        }
        if (block.type === 'ul') {
          return (
            <ul key={i} className="space-y-1.5 pl-0.5">
              {block.items.map((item, j) => {
                const symbolMatch = item.match(/^(✓|✅|⚠️|⚠|✗|✘|❌|x|X)\s+/);
                const accent: Accent = symbolMatch ? statusOf(symbolMatch[1]) : null;
                const body = symbolMatch ? item.slice(symbolMatch[0].length) : item;
                return (
                  <li key={j} className="flex gap-2 text-sm text-foreground/80 leading-relaxed">
                    {accent ? (
                      <span className={cn('w-4 shrink-0 text-center font-semibold', ACCENT_TEXT[accent])}>
                        {statusOf(symbolMatch![1]) === 'good' ? '✓' : accent === 'warn' ? '⚠' : '✗'}
                      </span>
                    ) : (
                      <span className="mt-[7px] h-1.5 w-1.5 shrink-0 rounded-full bg-primary/50" />
                    )}
                    <span><InlineText text={body} accent={accent} /></span>
                  </li>
                );
              })}
            </ul>
          );
        }
        return (
          <p key={i} className="text-sm text-foreground/80 leading-relaxed">
            <InlineText text={block.items[0]} />
          </p>
        );
      })}
    </div>
  );
}

export function AISummaryCard({
  page,
  role = 'admin',
  data,
  className,
  autoGenerate = true
}: AISummaryCardProps) {
  const { summary, isLoading, error, generateSummary, setSummaryDirect } = useAISummary({ page, role });
  const { user, profile } = useAuth();
  const insightsSettings = useAiInsightsSettings();
  const [isExpanded, setIsExpanded] = useState(false);

  // Cache scope: summaries are one org's financial figures viewed by one user.
  // localStorage survives logins on a shared browser, so the scope must be part
  // of every cache key.
  const cacheScope = `${user?.id ?? 'anon'}:${profile?.current_organization_id ?? 'no-org'}`;
  const cacheKey = useMemo(() => buildCacheKey(cacheScope, page, data), [cacheScope, page, data]);
  const periodKey = useMemo(
    () => currentAiInsightsPeriodKey(insightsSettings),
    [insightsSettings.mode, insightsSettings.weekday, insightsSettings.monthDay],
  );

  // One generation at a time. Page figures load in stages, and every stage
  // used to re-fire generation while the previous call was still in flight
  // (the cache is only written when a response lands) — the AI Usage log
  // showed 3 identical calls ~1s apart on a single page open.
  const inFlightRef = useRef(false);
  useEffect(() => {
    if (!isLoading) inFlightRef.current = false;
  }, [isLoading]);

  useEffect(() => {
    if (!autoGenerate || !data || Object.keys(data).length === 0) return;
    // Wait for auth before touching the cache — reading or writing under an
    // 'anon' scope would recreate the cross-account leak the scope prevents.
    if (!user?.id || !profile?.current_organization_id) return;
    // Wait for the SuperAdmin schedule before deciding — generating first and
    // discovering a reusable cached summary afterwards would waste the tokens
    // the setting exists to save.
    if (insightsSettings.isLoading) return;

    // Scheduled mode (daily / weekly / monthly): reuse the stored summary
    // while we are still inside the same regeneration period, regardless of
    // data changes or new sessions.
    if (periodKey) {
      const cached = readScheduleCache(cacheScope, page, role, periodKey);
      if (cached) {
        setSummaryDirect(normalizeAiSummaryGbp(cached));
        return;
      }
    } else {
      // Legacy per-session mode — check sessionStorage cache first
      try {
        const cached = sessionStorage.getItem(cacheKey);
        if (cached) {
          setSummaryDirect(normalizeAiSummaryGbp(cached));
          return;
        }
      } catch {}
    }

    if (inFlightRef.current) return;

    // Debounce so the page's figures settle before we spend tokens — each
    // data change cancels the pending call and re-arms, so exactly ONE
    // request fires ~1.2s after the last change (and with the final figures,
    // not a half-loaded snapshot).
    const timer = setTimeout(() => {
      if (inFlightRef.current) return;
      inFlightRef.current = true;
      generateSummary(data);
    }, 1200);
    return () => clearTimeout(timer);
  }, [page, autoGenerate, cacheKey, cacheScope, insightsSettings.isLoading, periodKey, user?.id, profile?.current_organization_id]);

  // Persist the generated summary (both caches — the mode may change later)
  useEffect(() => {
    if (summary && user?.id && profile?.current_organization_id) {
      try { sessionStorage.setItem(cacheKey, normalizeAiSummaryGbp(summary)); } catch {}
      writeScheduleCache(cacheScope, page, role, normalizeAiSummaryGbp(summary), periodKey);
    }
  }, [summary, cacheKey, cacheScope, page, role, periodKey, user?.id, profile?.current_organization_id]);

  const handleRefresh = () => {
    try { sessionStorage.removeItem(cacheKey); } catch {}
    clearScheduleCache(cacheScope, page, role);
    inFlightRef.current = true;
    generateSummary(data);
    setIsExpanded(false);
  };

  const isExpandable = !!summary && summary.length > 150;

  return (
    <div className={cn(
      'relative overflow-hidden rounded-xl border border-primary/15 bg-gradient-to-br from-primary/[0.07] via-background to-violet-500/[0.05] p-4 shadow-sm',
      className
    )}>
      {/* thin brand accent along the top edge */}
      <div className="pointer-events-none absolute inset-x-0 top-0 h-[2px] bg-gradient-to-r from-primary/70 via-violet-500/60 to-transparent" />

      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <div className={cn(
            'flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-primary to-violet-500 shadow-sm',
            isLoading && 'animate-pulse'
          )}>
            <Sparkles className="h-4 w-4 text-primary-foreground" />
          </div>
          <div className="leading-tight">
            <span className="text-sm font-semibold text-foreground">AI Insights</span>
            <p className="text-[11px] text-muted-foreground">
              {isLoading ? 'Analysing this page’s figures…' : 'Auto-generated from this page’s live figures'}
            </p>
          </div>
        </div>
        {/* In scheduled mode (SuperAdmin daily/weekly/monthly setting) insights
            regenerate only at period boundaries — a manual refresh would spend
            the tokens the setting exists to save, so the button is hidden. */}
        {!periodKey && (
          <Button
            variant="ghost"
            size="icon"
            onClick={handleRefresh}
            disabled={isLoading}
            className="h-7 w-7 text-muted-foreground hover:text-foreground"
            title="Regenerate insights"
          >
            <RefreshCw className={cn('h-3.5 w-3.5', isLoading && 'animate-spin')} />
          </Button>
        )}
      </div>

      {isLoading ? (
        <div className="space-y-2">
          <Skeleton className="h-3.5 w-full" />
          <Skeleton className="h-3.5 w-[92%]" />
          <Skeleton className="h-3.5 w-[80%]" />
          <Skeleton className="h-3.5 w-[55%]" />
        </div>
      ) : error ? (
        <div className="relative overflow-hidden rounded-lg border border-destructive/20 bg-destructive/5 px-3 py-2.5">
          {/* periodic light sweep so the state reads as temporary, not dead */}
          <div className="pointer-events-none absolute inset-0 animate-shimmer-sweep bg-gradient-to-r from-transparent via-destructive/10 to-transparent" />
          <div className="relative flex items-start justify-between gap-3">
            <div className="flex items-start gap-2 text-sm text-destructive">
              <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 animate-pulse-subtle" />
              <span>{error}</span>
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleRefresh}
              className="h-7 shrink-0 border-destructive/30 text-destructive hover:bg-destructive/10 hover:text-destructive"
            >
              Try again
            </Button>
          </div>
        </div>
      ) : summary ? (
        <div>
          <div className="relative">
            <div className={cn(
              'expand-animation',
              isExpanded ? 'expand-expanded' : 'expand-collapsed'
            )}>
              <SummaryText text={normalizeAiSummaryGbp(summary)} />
            </div>
            {/* soft fade instead of a hard cut while collapsed */}
            {isExpandable && !isExpanded && (
              <div className="pointer-events-none absolute inset-x-0 bottom-0 h-8 bg-gradient-to-t from-background to-transparent" />
            )}
          </div>
          {isExpandable && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="mt-2 inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-xs font-medium text-primary transition-colors hover:bg-primary/10 hover:text-primary"
            >
              {isExpanded ? (
                <>Show less <ChevronUp className="h-3.5 w-3.5" /></>
              ) : (
                <>Read full summary <ChevronDown className="h-3.5 w-3.5" /></>
              )}
            </button>
          )}
        </div>
      ) : (
        <div className="flex items-center justify-between gap-3">
          <p className="text-sm italic text-muted-foreground">
            No insights generated yet for this page.
          </p>
          <Button variant="outline" size="sm" onClick={handleRefresh} className="h-7 shrink-0 gap-1.5">
            <Sparkles className="h-3.5 w-3.5 text-primary" />
            Generate
          </Button>
        </div>
      )}
    </div>
  );
}
