const PDFDocument = require('pdfkit');
const { supabaseAdmin } = require('../../config/supabase');
const { formatDateDisplay } = require('./periodHelper');

/**
 * Structured PDF report generator — 8 CA-friendly report types.
 * Each report has its own data-fetching + professional PDF layout.
 */

// ── Shared TPI fetch ──

/**
 * Cursor-paginated fetch of completed TPIs on a payment plan within a date range.
 * Mirrors useTreatmentInsights so report totals match the Insights page.
 */
async function fetchCompletedTpisForReport(orgId, periodFrom, periodTo, locationId = null, columns = 'tpi_price, tpi_treatment_id, tpi_patient_nomenclature, tpi_payment_plan_id, location_id') {
  const PAGE_SIZE = 1000;
  const out = [];
  let cursor = null;
  const projection = columns.includes('tpi_id') ? columns : `tpi_id, ${columns}`;
  while (true) {
    let q = supabaseAdmin
      .from('treatment_plan_items')
      .select(projection)
      .eq('organization_id', orgId)
      .eq('tpi_completed', true)
      .not('tpi_payment_plan_id', 'is', null)
      .gte('tpi_completed_at', periodFrom)
      .lte('tpi_completed_at', periodTo + 'T23:59:59')
      .order('tpi_id')
      .limit(PAGE_SIZE);
    if (locationId) q = q.eq('location_id', locationId);
    if (cursor != null) q = q.gt('tpi_id', cursor);

    const { data: page, error } = await q;
    if (error) throw error;
    if (!page || page.length === 0) break;
    out.push(...page);
    if (page.length < PAGE_SIZE) break;
    cursor = page[page.length - 1].tpi_id;
  }
  return out;
}

// ── Shared PDF helpers ──

function fmt(val) {
  return '£' + (parseFloat(val) || 0).toLocaleString('en-GB', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function pct(val) {
  return (parseFloat(val) || 0).toFixed(1) + '%';
}

function addHeader(doc, title, subtitle, periodFrom, periodTo) {
  doc.rect(0, 0, 612, 85).fill('#6c5ce7');
  doc.fontSize(20).font('Helvetica-Bold').fillColor('#ffffff').text(title, 50, 22);
  doc.fontSize(10).font('Helvetica').fillColor('#e0d8ff').text(subtitle, 50, 48);
  doc.fontSize(9).fillColor('#c4bbff')
    .text(`Period: ${formatDateDisplay(periodFrom)} — ${formatDateDisplay(periodTo)}`, 50, 63);
  doc.moveDown(4);
  doc.fillColor('#111827');
}

function addFooter(doc) {
  const y = doc.page.height - 40;
  // Writing below the bottom margin (default 72pt) makes PDFKit insert a new
  // page before placing the text, which is why the footer was landing on a
  // blank page 2. Drop the bottom margin to 0 just for the footer write so
  // the text stays on the page we're finishing.
  const prevBottom = doc.page.margins.bottom;
  doc.page.margins.bottom = 0;
  doc.fontSize(7).font('Helvetica').fillColor('#9ca3af')
    .text(
      `Generated by DentPulse AI  •  ${new Date().toLocaleString('en-GB', { dateStyle: 'long', timeStyle: 'short' })}`,
      50, y,
      { align: 'center', width: 500, lineBreak: false }
    );
  doc.page.margins.bottom = prevBottom;
}

function addSectionTitle(doc, title) {
  if (doc.y > 700) doc.addPage();
  doc.moveDown(0.8);
  doc.fontSize(12).font('Helvetica-Bold').fillColor('#6c5ce7').text(title);
  doc.moveDown(0.3);
  doc.fillColor('#111827');
}

function addTable(doc, headers, rows, colWidths) {
  const startX = 50;
  const totalWidth = colWidths.reduce((s, w) => s + w, 0);
  let y = doc.y;

  // Header row
  doc.rect(startX, y, totalWidth, 20).fill('#f3f0ff');
  doc.fillColor('#374151');
  let x = startX;
  headers.forEach((h, i) => {
    doc.fontSize(8).font('Helvetica-Bold')
      .text(h, x + 4, y + 5, { width: colWidths[i] - 8, align: i === 0 ? 'left' : 'right' });
    x += colWidths[i];
  });
  y += 20;

  // Data rows
  for (let r = 0; r < rows.length; r++) {
    if (y > 720) {
      doc.addPage();
      addFooter(doc);
      y = 50;
    }
    const bg = r % 2 === 0 ? '#ffffff' : '#f9fafb';
    doc.rect(startX, y, totalWidth, 18).fill(bg);
    doc.fillColor('#111827');

    x = startX;
    const row = rows[r];
    row.forEach((cell, i) => {
      const isBold = String(cell).startsWith('£') || String(cell).includes('Total') || String(cell).includes('Net');
      doc.fontSize(8).font(isBold ? 'Helvetica-Bold' : 'Helvetica')
        .text(String(cell), x + 4, y + 4, { width: colWidths[i] - 8, align: i === 0 ? 'left' : 'right' });
      x += colWidths[i];
    });
    y += 18;
  }

  doc.rect(startX, y, totalWidth, 0.5).fill('#e5e7eb');
  doc.y = y + 8;
}

function addKeyValue(doc, label, value, bold) {
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text(label, { continued: true });
  doc.font(bold ? 'Helvetica-Bold' : 'Helvetica').fillColor('#111827').text('  ' + value);
  doc.moveDown(0.2);
}

// ── Report generators ──

async function generatePLReport(orgId, periodFrom, periodTo, doctorName) {
  // Revenue (production)
  const { data: revenue } = await supabaseAdmin.rpc('chart_get_production_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });

  // Profit
  const { data: profit } = await supabaseAdmin.rpc('chart_get_profit_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });

  let revData = revenue || [];
  let profData = profit || [];

  if (doctorName) {
    const lower = doctorName.toLowerCase();
    revData = revData.filter(p => p.provider_name?.toLowerCase().includes(lower));
    profData = profData.filter(p => p.provider_name?.toLowerCase().includes(lower));
  }

  const totalRevenue = revData.reduce((s, p) => s + parseFloat(p.production_amount || 0), 0);
  const totalProfit = profData.reduce((s, p) => s + parseFloat(p.periodic_profit || 0), 0);
  const scope = doctorName || 'Whole Practice';

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Profit & Loss Report', scope, periodFrom, periodTo);

  // Summary
  addSectionTitle(doc, 'Financial Summary');
  addKeyValue(doc, 'Total Revenue:', fmt(totalRevenue), true);
  addKeyValue(doc, 'Total Profit:', fmt(totalProfit), true);
  addKeyValue(doc, 'Profit Margin:', totalRevenue > 0 ? pct((totalProfit / totalRevenue) * 100) : '0.0%', true);

  // Revenue by provider
  addSectionTitle(doc, 'Revenue by Provider');
  const revRows = revData.slice(0, 25).map(p => [
    p.provider_name || 'Unknown', fmt(p.production_amount), `#${p.rank || '-'}`
  ]);
  if (revRows.length > 0) {
    revRows.push(['Total', fmt(totalRevenue), '']);
    addTable(doc, ['Provider', 'Revenue', 'Rank'], revRows, [250, 150, 95]);
  }

  // Profit by provider
  addSectionTitle(doc, 'Profit by Provider');
  const profRows = profData.slice(0, 25).map(p => [
    p.provider_name || 'Unknown', fmt(p.periodic_profit), pct(p.profit_percent || 0)
  ]);
  if (profRows.length > 0) {
    profRows.push(['Total', fmt(totalProfit), '']);
    addTable(doc, ['Provider', 'Profit', 'Margin %'], profRows, [250, 150, 95]);
  }

  addFooter(doc);
  return doc;
}

async function generateRevenueReport(orgId, periodFrom, periodTo, doctorName) {
  const { data } = await supabaseAdmin.rpc('chart_get_production_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });

  let providers = data || [];
  if (doctorName) {
    const lower = doctorName.toLowerCase();
    providers = providers.filter(p => p.provider_name?.toLowerCase().includes(lower));
  }

  const total = providers.reduce((s, p) => s + parseFloat(p.production_amount || 0), 0);
  const scope = doctorName || 'Whole Practice';

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Revenue Report', scope, periodFrom, periodTo);

  addSectionTitle(doc, 'Summary');
  addKeyValue(doc, 'Total Revenue:', fmt(total), true);
  addKeyValue(doc, 'Providers:', String(providers.length));

  addSectionTitle(doc, 'Revenue by Provider');
  const rows = providers.slice(0, 30).map((p, i) => [
    p.provider_name || 'Unknown',
    fmt(p.production_amount),
    total > 0 ? pct((parseFloat(p.production_amount || 0) / total) * 100) : '0.0%',
    `#${p.rank || i + 1}`,
  ]);
  rows.push(['Total', fmt(total), '100.0%', '']);
  addTable(doc, ['Provider', 'Revenue', '% of Total', 'Rank'], rows, [200, 120, 90, 85]);

  addFooter(doc);
  return doc;
}

async function generateCashflowReport(orgId, periodFrom, periodTo) {
  const { data } = await supabaseAdmin.rpc('get_cashflow_overview_weekly', {
    p_organization_id: orgId, p_tenant_ids: [],
    p_anchor_date: periodTo, p_this_start: periodFrom, p_this_end: periodTo,
    p_last_start: periodFrom, p_last_end: periodTo,
  });

  const cf = data?.[0] || data || {};

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Cashflow Statement', 'Whole Practice', periodFrom, periodTo);

  addSectionTitle(doc, 'Cashflow Summary');
  const rows = [
    ['Cash Received', fmt(cf.received_this || 0)],
    ['Cash Paid', fmt(cf.paid_this || 0)],
    ['Net Cashflow', fmt(cf.net_this || 0)],
    ['Closing Balance', fmt(cf.closing_this || 0)],
  ];
  addTable(doc, ['Description', 'Amount'], rows, [300, 195]);

  addFooter(doc);
  return doc;
}

async function generateProviderReport(orgId, periodFrom, periodTo, doctorName) {
  if (!doctorName) {
    return generateRevenueReport(orgId, periodFrom, periodTo, null);
  }

  const lower = doctorName.toLowerCase();

  // Production
  const { data: prod } = await supabaseAdmin.rpc('chart_get_production_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });
  const provProd = (prod || []).find(p => p.provider_name?.toLowerCase().includes(lower));

  // Profit
  const { data: prof } = await supabaseAdmin.rpc('chart_get_profit_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });
  const provProf = (prof || []).find(p => p.provider_name?.toLowerCase().includes(lower));

  // Performance
  const { data: perf } = await supabaseAdmin.rpc('chart_get_associate_performance_metrics', {
    p_start_date: periodFrom, p_end_date: periodTo,
    p_organization_id: orgId, p_provider_type: null, p_location_id: null,
  });
  const provPerf = (perf || []).find(p => p.provider_name?.toLowerCase().includes(lower));

  // Patients
  const { data: patients } = await supabaseAdmin.rpc('get_total_distinct_patients', {
    p_organization_id: orgId, p_start_date: periodFrom, p_end_date: periodTo,
    p_provider_type: null, p_location_id: null,
  });

  const name = provProd?.provider_name || doctorName;

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Provider Performance Report', name, periodFrom, periodTo);

  addSectionTitle(doc, 'Key Metrics');
  const metrics = [
    ['Production Revenue', fmt(provProd?.production_amount || 0)],
    ['Days Worked', String(provProd?.days_worked || 0)],
    ['Avg Daily Production', fmt(provProd?.avg_daily_production || 0)],
    ['Profit', fmt(provProf?.periodic_profit || 0)],
    ['Profit Margin', pct(provProf?.profit_percent || 0)],
    ['Profit Per Day', fmt(provProf?.pl_per_day || 0)],
    ['Performance vs Target', pct(provPerf?.performance_percent || 0)],
    ['Target Gap', fmt(provPerf?.target_gap || 0)],
    ['Revenue Rank', `#${provProd?.rank || '-'}`],
  ];
  addTable(doc, ['Metric', 'Value'], metrics, [300, 195]);

  addFooter(doc);
  return doc;
}

async function generateTreatmentReport(orgId, periodFrom, periodTo) {
  // Match Treatment Insights — fetch all completed-on-plan TPIs paginated, then
  // join treatments for the category and payment_plans for the payor name.
  const tpis = await fetchCompletedTpisForReport(orgId, periodFrom, periodTo, null);

  const treatmentIds = Array.from(new Set(tpis.map(t => t.tpi_treatment_id).filter(Boolean)));
  const categoryByTreatment = new Map();
  if (treatmentIds.length > 0) {
    const { data: treatments } = await supabaseAdmin
      .from('treatments')
      .select('external_id, treatment_category')
      .eq('organization_id', orgId)
      .in('external_id', treatmentIds);
    for (const t of treatments || []) {
      categoryByTreatment.set(String(t.external_id), t.treatment_category || 'Uncategorized');
    }
  }

  const planIds = Array.from(new Set(tpis.map(t => t.tpi_payment_plan_id).filter(v => v != null)));
  const planNameById = new Map();
  if (planIds.length > 0) {
    const { data: plans } = await supabaseAdmin
      .from('payment_plans')
      .select('pp_id, pp_name')
      .eq('organization_id', orgId)
      .in('pp_id', planIds);
    for (const p of plans || []) {
      planNameById.set(String(p.pp_id), p.pp_name || `Plan ${p.pp_id}`);
    }
  }

  const byCategory = {};
  const byPayor = {};
  let total = 0;

  for (const item of tpis) {
    const cat = categoryByTreatment.get(String(item.tpi_treatment_id))
      || item.tpi_patient_nomenclature
      || 'Uncategorized';
    const payor = item.tpi_payment_plan_id != null
      ? (planNameById.get(String(item.tpi_payment_plan_id)) || `Plan ${item.tpi_payment_plan_id}`)
      : 'Other';
    const price = parseFloat(item.tpi_price || 0);
    byCategory[cat] = (byCategory[cat] || 0) + price;
    byPayor[payor] = (byPayor[payor] || 0) + price;
    total += price;
  }

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Treatment Revenue Report', 'Whole Practice', periodFrom, periodTo);

  addSectionTitle(doc, 'Summary');
  addKeyValue(doc, 'Total Treatment Revenue:', fmt(total), true);
  addKeyValue(doc, 'Categories:', String(Object.keys(byCategory).length));

  addSectionTitle(doc, 'Revenue by Category');
  const catRows = Object.entries(byCategory)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 20)
    .map(([cat, val]) => [cat, fmt(val), total > 0 ? pct((val / total) * 100) : '0.0%']);
  catRows.push(['Total', fmt(total), '100.0%']);
  addTable(doc, ['Category', 'Revenue', '% of Total'], catRows, [250, 130, 115]);

  addSectionTitle(doc, 'Revenue by Payor Type');
  const payorRows = Object.entries(byPayor)
    .sort(([, a], [, b]) => b - a)
    .map(([payor, val]) => [payor, fmt(val), total > 0 ? pct((val / total) * 100) : '0.0%']);
  addTable(doc, ['Payor', 'Revenue', '% of Total'], payorRows, [250, 130, 115]);

  addFooter(doc);
  return doc;
}

async function generateChairReport(orgId, periodFrom, periodTo) {
  const prevStart = new Date(periodFrom);
  const prevEnd = new Date(periodTo);
  const diff = prevEnd - prevStart;
  prevStart.setTime(prevStart.getTime() - diff);
  prevEnd.setTime(prevEnd.getTime() - diff);

  const { data } = await supabaseAdmin.rpc('get_chair_metrics', {
    _organization_id: orgId,
    _start_date: periodFrom, _end_date: periodTo,
    _prev_start_date: prevStart.toISOString().split('T')[0],
    _prev_end_date: prevEnd.toISOString().split('T')[0],
  });

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Chair Utilisation Report', 'All Locations', periodFrom, periodTo);

  addSectionTitle(doc, 'Chair Metrics by Location');
  const rows = (data || []).map(c => [
    c.location_name || 'Unknown',
    String(c.chairs_count || 0),
    pct(c.occupancy_pct),
    pct(c.utilisation_pct),
    fmt(c.revenue_per_chair),
    fmt(c.revenue),
  ]);
  if (rows.length > 0) {
    addTable(doc, ['Location', 'Chairs', 'Occupancy', 'Utilisation', 'Rev/Chair', 'Total Revenue'], rows, [130, 50, 70, 70, 85, 90]);
  } else {
    doc.fontSize(10).font('Helvetica').text('No chair data available for this period.');
  }

  addFooter(doc);
  return doc;
}

async function generateLocationReport(orgId, periodFrom, periodTo) {
  const { data: locations } = await supabaseAdmin
    .from('practice_locations')
    .select('id, location_name')
    .eq('organization_id', orgId).is('deleted_at', null);

  const production = await fetchCompletedTpisForReport(orgId, periodFrom, periodTo, null, 'tpi_price, location_id');

  const revByLoc = {};
  for (const item of production) {
    const locId = item.location_id || 'unknown';
    revByLoc[locId] = (revByLoc[locId] || 0) + parseFloat(item.tpi_price || 0);
  }

  const totalRev = Object.values(revByLoc).reduce((s, v) => s + v, 0);

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, 'Location Performance Report', 'All Locations', periodFrom, periodTo);

  addSectionTitle(doc, 'Summary');
  addKeyValue(doc, 'Total Revenue:', fmt(totalRev), true);
  addKeyValue(doc, 'Locations:', String((locations || []).length));

  addSectionTitle(doc, 'Revenue by Location');
  const rows = (locations || [])
    .map(loc => ({
      name: loc.location_name,
      rev: revByLoc[loc.id] || 0,
    }))
    .sort((a, b) => b.rev - a.rev)
    .map((loc, i) => [
      loc.name, fmt(loc.rev),
      totalRev > 0 ? pct((loc.rev / totalRev) * 100) : '0.0%',
      `#${i + 1}`,
    ]);
  rows.push(['Total', fmt(totalRev), '100.0%', '']);
  addTable(doc, ['Location', 'Revenue', '% of Total', 'Rank'], rows, [200, 120, 90, 85]);

  addFooter(doc);
  return doc;
}

async function generateMultiPeriodReport(orgId, periods, reportType, doctorName) {
  const metric = reportType === 'pl' ? 'profit' : 'revenue';
  const rpcName = metric === 'profit' ? 'chart_get_profit_metrics' : 'chart_get_production_metrics';
  const valKey = metric === 'profit' ? 'periodic_profit' : 'production_amount';
  const periodHelper = require('./periodHelper');

  const resolvedPeriods = (periods || []).map(p => {
    const resolved = periodHelper.resolveperiodLabel(p);
    return resolved || { from: p, to: p, label: p };
  });

  const periodTotals = [];
  for (const period of resolvedPeriods) {
    const { data } = await supabaseAdmin.rpc(rpcName, {
      p_start_date: period.from, p_end_date: period.to,
      p_organization_id: orgId, p_provider_type: null, p_location_id: null,
    });
    let filtered = data || [];
    if (doctorName) {
      const lower = doctorName.toLowerCase();
      filtered = filtered.filter(p => p.provider_name?.toLowerCase().includes(lower));
    }
    const total = filtered.reduce((s, p) => s + parseFloat(p[valKey] || 0), 0);
    periodTotals.push({ label: period.label, from: period.from, to: period.to, total });
  }

  const scope = doctorName || 'Whole Practice';
  const label = reportType === 'pl' ? 'P&L' : 'Revenue';

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  addHeader(doc, `Multi-Period ${label} Comparison`, scope,
    resolvedPeriods[0]?.from || '', resolvedPeriods[resolvedPeriods.length - 1]?.to || '');

  addSectionTitle(doc, 'Period Comparison');
  const rows = periodTotals.map(p => [p.label, fmt(p.total)]);
  addTable(doc, ['Period', label], rows, [300, 195]);

  // Variance
  if (periodTotals.length >= 2) {
    addSectionTitle(doc, 'Period-over-Period Change');
    const varRows = [];
    for (let i = 1; i < periodTotals.length; i++) {
      const prev = periodTotals[i - 1];
      const curr = periodTotals[i];
      const delta = curr.total - prev.total;
      const pctChg = prev.total !== 0 ? ((delta / Math.abs(prev.total)) * 100).toFixed(1) : '—';
      const arrow = delta >= 0 ? '↑' : '↓';
      varRows.push([`${prev.label} → ${curr.label}`, fmt(delta), `${arrow} ${Math.abs(pctChg)}%`]);
    }
    addTable(doc, ['Comparison', 'Change', '% Change'], varRows, [250, 130, 115]);
  }

  addFooter(doc);
  return doc;
}

// ── Main dispatcher ──

async function generateReport(reportType, orgId, periodFrom, periodTo, doctorName, periods) {
  switch (reportType) {
    case 'pl':
      return generatePLReport(orgId, periodFrom, periodTo, doctorName);
    case 'revenue':
      return generateRevenueReport(orgId, periodFrom, periodTo, doctorName);
    case 'cashflow':
      return generateCashflowReport(orgId, periodFrom, periodTo);
    case 'provider':
      return generateProviderReport(orgId, periodFrom, periodTo, doctorName);
    case 'treatment':
      return generateTreatmentReport(orgId, periodFrom, periodTo);
    case 'chair':
    case 'chairs':
      return generateChairReport(orgId, periodFrom, periodTo);
    case 'location':
    case 'locations':
      return generateLocationReport(orgId, periodFrom, periodTo);
    case 'multi_period':
      return generateMultiPeriodReport(orgId, periods, 'revenue', doctorName);
    default:
      return generateRevenueReport(orgId, periodFrom, periodTo, doctorName);
  }
}

module.exports = { generateReport };
