export type PeEconomicAssumptions = {
  membershipServiceCostAnnual: number;
  defaultCac: number;
  commitmentRateWindowDays: number;
  commitmentRateClinicianWindowDays: number;
  commitmentRateStandardWindowsDays: number[];
  leakageUnscheduledThresholdDays: number;
  growthLeversTrailingMonths: number;
  growthLeversBenchmarkMethod: 'group_top' | 'configured_target';
  growthLeversTargetVisitFrequency: number | null;
  growthLeversTargetValuePerVisit: number | null;
  growthLeversTargetTenureYears: number | null;
  growthLeversTargetProjectedLifetimeYears: number | null;
  cltvAcquisitionMinSample: number;
  collectionRateTrailingMonths: number;
  cashLeakageCollectionWindowDays: number;
  agingBucketBoundaryDays: number[];
  retentionDriftingVisitGapDays: number;
  retentionLapsedRecallOverdueDays: number;
  retentionLapsedVisitGapDays: number;
  retentionEffectivelyLostRecallOverdueDays: number;
  retentionEffectivelyLostVisitGapDays: number;
  reactivationMinContributionAtRiskGbp: number;
  reactivationRecoveryContributionWindowDays: number;
  reactivationHighValueAtRiskGbp: number;
  reactivationWorklistTrailingMonths: number;
  recommendedActionHighOpportunityWeightedGbp: number;
  recommendedActionHighQualityScore: number;
  recommendedActionLowQualityScore: number;
  projectedLifetimeYearsActive: number;
  projectedLifetimeYearsDrifting: number;
  projectedLifetimeYearsLapsed: number;
  projectedLifetimeYearsEffectivelyLost: number;
  cltvProjectionHorizonYears: number;
  cltvProjectionDiscountRate: number;
  modelledVisitsPerYearCap: number;
  modelledMinVisitsPerYearActive: number;
  modelledInactiveRetentionFactor: number;
  modelledFullEngagementVisitsPerYear: number;
  modelledQualityScorePlanBonus: number;
  journeyMinPlannedEvents: number;
  journeyMinTotalFunnelEvents: number;
};

export type PeConversionProbabilitiesSummary = {
  practiceId: string;
  readOnly: boolean;
  readOnlyReason: string;
  modelTier: string;
  windowDays: number;
  commitmentRate: number;
  commitmentRatePct: number;
  confidence: number;
  tierNote: string;
  eligibleItemCount: number;
  committedItemCount: number;
  totalEligibleValue: number;
  committedValueWithinWindow: number;
  openPlanCount: number;
  openPlanGrossGbp: number;
  weightedFormula: string;
  standardWindowsDays: number[];
};
